// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARKjbiMi9tm5RBoZ-paEUMoJjUZcxfTOE',
    appId: '1:474540526660:web:c4d40dbf6b3ae55cf44011',
    messagingSenderId: '474540526660',
    projectId: 'flutter-chat-application-bc68a',
    authDomain: 'flutter-chat-application-bc68a.firebaseapp.com',
    storageBucket: 'flutter-chat-application-bc68a.firebasestorage.app',
    measurementId: 'G-FNLP1B42PB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVkrJst-MWHDJqgEfGopzeSUTJWCRj5s0',
    appId: '1:474540526660:android:33fb285c78b15f29f44011',
    messagingSenderId: '474540526660',
    projectId: 'flutter-chat-application-bc68a',
    storageBucket: 'flutter-chat-application-bc68a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArZJKwZcoBO-NJAEqkBwtvgSVEYs5iPA0',
    appId: '1:474540526660:ios:f0280e0618911afdf44011',
    messagingSenderId: '474540526660',
    projectId: 'flutter-chat-application-bc68a',
    storageBucket: 'flutter-chat-application-bc68a.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArZJKwZcoBO-NJAEqkBwtvgSVEYs5iPA0',
    appId: '1:474540526660:ios:f0280e0618911afdf44011',
    messagingSenderId: '474540526660',
    projectId: 'flutter-chat-application-bc68a',
    storageBucket: 'flutter-chat-application-bc68a.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARKjbiMi9tm5RBoZ-paEUMoJjUZcxfTOE',
    appId: '1:474540526660:web:6879539690fae394f44011',
    messagingSenderId: '474540526660',
    projectId: 'flutter-chat-application-bc68a',
    authDomain: 'flutter-chat-application-bc68a.firebaseapp.com',
    storageBucket: 'flutter-chat-application-bc68a.firebasestorage.app',
    measurementId: 'G-K483D4W7BL',
  );
}
